<link type="text/css" rel="stylesheet" href="sign-up.css">
<div id="retour">
    <a href="index.php"><< Retour</a>
</div>

<form action="do-sign-up.php" method="post">
    <div>
        <h1>Nom d'utilisateur</h1>
        <input class="light"
               <?php if ($ename == "name") { ?>style='border-top:2px solid red;border-bottom:2px solid red;border-left:2px solid red;border-right:2px solid red;' <?php } ?>
               onclick="remettreNormalement(this)" type="text" name="username" value="" placeholder="" required>
        <?php if ($ename == "name") { ?>
            <p>Un utilisateur avec ce nom existe déja, veuillez entrer un autre nom.</p>
        <?php } ?>
    </div>

    <div>
        <h1>Mot de passe</h1>
        <input
            <?php if ($emdp == "mdp") { ?>style='border-top:2px solid red;border-bottom:2px solid red;border-left:2px solid red;border-right:2px solid red;' <?php } ?>
            onclick="remettreNormalement(this)" class="password" type="password" name="password" value="" placeholder=""
            required>
    </div>
    <div>
        <h1>Répéter le mot de passe</h1>
        <input
            <?php if ($emdp == "mdp") { ?>style='border-top:2px solid red;border-bottom:2px solid red;border-left:2px solid red;border-right:2px solid red;' <?php } ?>
            onclick="remettreNormalement(this)" class="password" type="password" name="passwordx" value=""
            placeholder="" required>
        <button class="unmask" type="button" title="Afficher le mot de passe.">Unmask</button>
        <?php if ($emdp == "mdp") { ?>
            <p>Les deux mots de passe ne correspondent pas.</p>
        <?php } ?>
    </div>

    <div>
        <h1>Prénom</h1>
        <input class="light" type="text" name="firstname" value="" placeholder="" required>
    </div>

    <div>
        <h1>Nom de famille</h1>
        <input class="light" type="text" name="lastname" value="" placeholder="" required>
    </div>

    <div>
        <h1>E-mail</h1>
        <input class="light"
               <?php if ($eemail == "email") { ?>style='border-top:2px solid red;border-bottom:2px solid red;border-left:2px solid red;border-right:2px solid red;' <?php } ?>
               onclick="remettreNormalement(this)" type="text" name="email" value="" placeholder="" required>
        <?php if ($eemail == "email") { ?>
            <p>L'E-mail n'est pas valide.</p>
        <?php } ?>
    </div>
    <div>
        <br>
    </div>
    <input type="submit" name="submit" value="Créer">
</form>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script id="rendered-js">
    $('.unmask').on('click', function () {
        affiche();
    });

    function remettreNormalement(elm) {
        elm.setAttribute('style', 'border-top:;border-bottom:;border-left:;border-right:;');
    }

    function affiche() {
        var p = document.getElementsByClassName('password');
        if (p[0].type == "password" && p[1].type == "password") {
            p[0].type = "text";
            p[1].type = "text";
        } else {
            p[0].type = "password";
            p[1].type = "password";
        }
    }
</script>
